# Generated by Django 4.0.4 on 2022-06-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=40, unique=True)),
                ('genero_juego', models.CharField(max_length=40)),
                ('desarrollador', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=40)),
                ('fecha_review', models.DateField(auto_now_add=True)),
                ('titulo_review', models.CharField(max_length=40)),
                ('contenido_review', models.CharField(max_length=200)),
                ('puntaje_review', models.IntegerField()),
                ('juego_review', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=40, unique=True)),
                ('email_usuario', models.EmailField(max_length=40)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
